version: 3.2.{build}

image: Visual Studio 2017

configuration: Debug

init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
- '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"'
- ps: (New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/appveyor/ci/master/scripts/hot-fixes/vs2017-uwp-scale-100-fix/Microsoft.AppxPackage.Targets', "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppxPackage.Targets")
    
before_build:
- msbuild src\MoneyFox.sln /t:restore
    
build:
  parallel: true
  verbosity: minimal
  
test_script:
- cmd: '%xunit20%\xunit.console.x86 "C:\projects\moneyfox\Src\MoneyFox.Business.Tests\bin\Debug\net47\MoneyFox.Business.Tests.dll" -appveyor'
- cmd: dotnet test C:\projects\moneyfox\Src\MoneyFox.DataAccess.Tests\MoneyFox.DataAccess.Tests.csproj --no-build

environment:
  JavaSdkDirectory: C:\Program Files (x86)\Java\jdk1.8.0
